13ый спринт
Max-Jordan/java-shareit pull request #1
Opened 2023-01-13 16:28 UTC by Max-Jordan

2023-01-14 12:36 UTC, Frilock requested changes
Добрый день, мне в целом все понравилось, особой критики не вижу, написал ряд комментариев, которые в целом идут как "можно лучше". Жду новую версию, по возможности, посмотри что написал

2023-01-14 12:36 UTC, Frilock commented on pom.xml
> +			<version>3.8.1</version>
Версию лучше в properties перенести, как делали в прошлом проекте

2023-01-14 12:36 UTC, Frilock commented on src/main/java/ru/practicum/shareit/item/ItemRepositoryImpl.java
> +    private final HashMap<Long, Item> itemStore;
По хорошему правильнее объявлять     private final Map<Long, Item> itemStore; А когда уже инициализируешь - указывать new HashMap

2023-01-14 12:36 UTC, Frilock commented on src/main/java/ru/practicum/shareit/item/ItemRepositoryImpl.java
> +                        x.getName().toLowerCase().contains(name.toLowerCase()) ||
Можно заменить на StringUtils.equalsIgnoreCase

2023-01-14 12:36 UTC, Frilock commented on src/main/java/ru/practicum/shareit/item/ItemServiceImpl.java
> +        if (!StringUtils.isEmpty(item.getDescription())) {
Тут конструкции можно заменить на на Optional.ofNullable(...).ifPresent(...) будет выглядеть компактнее

2023-01-14 12:36 UTC, Frilock commented on src/main/java/ru/practicum/shareit/mapper/Mapper.java
> +public class Mapper {
Лучше назвать ItemMapper, а метод - MapToDto или наоборот MapToEntity, чтобы более понятно было по названию что делает класс и метод

2023-01-14 12:36 UTC, Frilock commented on src/main/java/ru/practicum/shareit/user/User.java
> +    private final Map<Long, Item> items = new HashMap<>();
Вообще бы эту логику в сервис перенести, а в этом классе толя поля оставить. Чтобы было четкое разделение model - dao - service - controller (возможны разные вариации)

2023-01-14 12:36 UTC, Frilock commented on src/main/java/ru/practicum/shareit/user/UserController.java
> +    public User saveUser(
в 1 строчку влезает, переносы не нужны. Кроме того, а будет ли аннотация Valid работать без Validated над контроллером? Проверял этот момент?

2023-01-14 12:36 UTC, Frilock commented on src/main/java/ru/practicum/shareit/user/UserServiceImpl.java
> +        if (user.getName() != null) {
Данную конструкцию можно заменить на Optional.ofNullable(...).ifPresent(...) будет выглядеть компактнее

2023-01-14 14:52 UTC, Max-Jordan commented on src/main/java/ru/practicum/shareit/item/ItemRepositoryImpl.java
> +    private final HashMap<Long, Item> itemStore;
Не совсем понимаю данный комментарий, данное поле инициализируется в конструкторе

2023-01-14 15:04 UTC, Max-Jordan commented on src/main/java/ru/practicum/shareit/user/User.java
> +    private final Map<Long, Item> items = new HashMap<>();
Какую именно логику перенести в сервис? По добавлению, изменению и получению вещей в мапе?

2023-01-15 12:44 UTC, Frilock requested changes
Добрый день, почти все ок, 2 комментария оставил посмотри пожалуйста

2023-01-15 12:44 UTC, Frilock commented on pom.xml
> -			<version>3.8.1</version>
А как у тебя это собралось?) По идее ты должен был в блоке version указать 
<version>${org.apache.commons.version}</version>

2023-01-15 12:44 UTC, Frilock commented on src/main/java/ru/practicum/shareit/item/ItemServiceImpl.java
> +        if (Optional.ofNullable(item.getAvailable()).isPresent()) {
Вот у тебя так
if (Optional.ofNullable(item.getAvailable()).isPresent()) {
            updateItem.setAvailable(item.getAvailable());
        }
        
        А можно - Optional.ofNullable(item.getAvailable).ifPresent(updateItem::setAvailable);
        Так компактнее, не правда ли? Попробуй поразбираться

2023-01-15 12:44 UTC, Frilock commented on src/main/java/ru/practicum/shareit/user/UserServiceImpl.java
> +
Лишняя пустая строка

2023-01-16 10:51 UTC, Frilock approved these changes
Принял работу, но по моему ты не до конца разобрался с тем что я тебя просил в pom сделать.  https://javarush.com/groups/posts/3119-java-proekt-ot-a-do-ja-vse-chto-vih-khoteli-znatjh-o-maven

2023-01-16 10:52 UTC, Frilock approved these changes
Принято

2023-01-16 16:02 UTC, merged